### ISSUE TITLE
throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);

### ISSUE THREAD

**Issue by ghost** [csepulv/electron-with-create-react-app#22]
I have run this project using `npm run dev`, the app ran fine, but I also got this output:

> 
> [WARN] No ENV file found
> 03:14:29 electron.1   |  starting electron
> 03:14:30 react.1      |  > electron-with-create-react-app@0.1.0 start C:\Users\G\Downloads\electron-with-create-react-app-master
> 03:14:30 react.1      |  > react-scripts start
> 03:14:34 react.1      |  Something is already running on port 3000.
> [DONE] Killing all processes with signal  null
> internal/util.js:186
>   throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);
>   ^
> 
> Error [ERR_UNKNOWN_SIGNAL]: Unknown signal: null
>     at convertToValidSignal (internal/util.js:186:9)
>     at ChildProcess.kill (internal/child_process.js:379:5)
>     at EventEmitter.<anonymous> (C:\Users\G\Downloads\electron-with-create-react-app-master\node_modules\foreman\lib\proc.js:54:11)
>     at emitOne (events.js:121:20)
>     at EventEmitter.emit (events.js:211:7)
>     at ChildProcess.<anonymous> (C:\Users\G\Downloads\electron-with-create-react-app-master\node_modules\foreman\lib\proc.js:50:13)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! electron-with-create-react-app@0.1.0 dev: `nf start -p 3000`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron-with-create-react-app@0.1.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\G\AppData\Roaming\npm-cache\_logs\2018-04-28T23_14_34_096Z-debug.log

Is this normal?

**Comment by csepulv** [comment]
It isn't normal. Do you have something else running on port 3000? You could edit `package.json` and change the port to something else to see if you still get the error.

**Comment by giorgim** [comment]
@csepulv No there is nothing on port 3000.
I noticed when it does it. The first time I run the app it doesn't produce this error.
As soon as I closed the app using 'x' button, I got this message. 
And then each time I run app I see it now (the app runs though, just the message is there).
ps. I am running on windows.

**Comment by csepulv** [comment]
`npm run dev` runs a few processes. I wouldn't stop by closing/exiting the window, but press Cntrl-C in your command line (terminal) to kill all the processes. It seems the window exit only kills the electron process, but leaves the react dev server running on port 3000. 

Task Manager may let you find/kill the runaway process, but if you use Cntrl-C it should work. 

In production, with a packaged and installed app, closing the window would be fine as you wouldn't have the react/webpack dev server running.

**Comment by gabriel-dehan** [comment]
Not exactly the same issue but I had the same error (when starting tho) and it was simply because I had changed the path to the `electron-wait-react` path and didn't update the Procfile, might be useful for posterity. 

Hope you have found what was bothering you tho :pray:
